// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: grpc/proto.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *BidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ResultRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"` // "success", "fail", or "exception"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *BidResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ongoing" or "finished"
	Winner        string                 `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
	HighestBid    int64                  `protobuf:"varint,3,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	IsAuctionOver bool                   `protobuf:"varint,4,opt,name=isAuctionOver,proto3" json:"isAuctionOver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultResponse) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *ResultResponse) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ResultResponse) GetIsAuctionOver() bool {
	if x != nil {
		return x.IsAuctionOver
	}
	return false
}

type ReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"` // "bid" or "state"
	ClientID      string                 `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	HighestBid    int64                  `protobuf:"varint,4,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	Winner        string                 `protobuf:"bytes,5,opt,name=winner,proto3" json:"winner,omitempty"`
	IsAuctionOver bool                   `protobuf:"varint,6,opt,name=isAuctionOver,proto3" json:"isAuctionOver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ReplicationRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ReplicationRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReplicationRequest) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicationRequest) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *ReplicationRequest) GetIsAuctionOver() bool {
	if x != nil {
		return x.IsAuctionOver
	}
	return false
}

type ReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	mi := &file_grpc_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_grpc_proto_proto protoreflect.FileDescriptor

const file_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x10grpc/proto.proto\"@\n" +
	"\n" +
	"BidRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"+\n" +
	"\rResultRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\"\x1f\n" +
	"\vBidResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack\"\x86\x01\n" +
	"\x0eResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\tR\x06winner\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12$\n" +
	"\risAuctionOver\x18\x04 \x01(\bR\risAuctionOver\"\xc4\x01\n" +
	"\x12ReplicationRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1a\n" +
	"\bclientID\x18\x02 \x01(\tR\bclientID\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x04 \x01(\x03R\n" +
	"highestBid\x12\x16\n" +
	"\x06winner\x18\x05 \x01(\tR\x06winner\x12$\n" +
	"\risAuctionOver\x18\x06 \x01(\bR\risAuctionOver\"/\n" +
	"\x13ReplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x95\x01\n" +
	"\x0eAuctionService\x12 \n" +
	"\x03Bid\x12\v.BidRequest\x1a\f.BidResponse\x12)\n" +
	"\x06Result\x12\x0e.ResultRequest\x1a\x0f.ResultResponse\x126\n" +
	"\tReplicate\x12\x13.ReplicationRequest\x1a\x14.ReplicationResponseB\x10Z\x0eITU/grpc/protob\x06proto3"

var (
	file_grpc_proto_proto_rawDescOnce sync.Once
	file_grpc_proto_proto_rawDescData []byte
)

func file_grpc_proto_proto_rawDescGZIP() []byte {
	file_grpc_proto_proto_rawDescOnce.Do(func() {
		file_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)))
	})
	return file_grpc_proto_proto_rawDescData
}

var file_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_proto_proto_goTypes = []any{
	(*BidRequest)(nil),          // 0: BidRequest
	(*ResultRequest)(nil),       // 1: ResultRequest
	(*BidResponse)(nil),         // 2: BidResponse
	(*ResultResponse)(nil),      // 3: ResultResponse
	(*ReplicationRequest)(nil),  // 4: ReplicationRequest
	(*ReplicationResponse)(nil), // 5: ReplicationResponse
}
var file_grpc_proto_proto_depIdxs = []int32{
	0, // 0: AuctionService.Bid:input_type -> BidRequest
	1, // 1: AuctionService.Result:input_type -> ResultRequest
	4, // 2: AuctionService.Replicate:input_type -> ReplicationRequest
	2, // 3: AuctionService.Bid:output_type -> BidResponse
	3, // 4: AuctionService.Result:output_type -> ResultResponse
	5, // 5: AuctionService.Replicate:output_type -> ReplicationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_proto_init() }
func file_grpc_proto_proto_init() {
	if File_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_proto_goTypes,
		DependencyIndexes: file_grpc_proto_proto_depIdxs,
		MessageInfos:      file_grpc_proto_proto_msgTypes,
	}.Build()
	File_grpc_proto_proto = out.File
	file_grpc_proto_proto_goTypes = nil
	file_grpc_proto_proto_depIdxs = nil
}
