// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GangnamStyle_Bid_FullMethodName    = "/gangnamStyle/bid"
	GangnamStyle_Result_FullMethodName = "/gangnamStyle/result"
	GangnamStyle_Bully_FullMethodName  = "/gangnamStyle/bully"
)

// GangnamStyleClient is the client API for GangnamStyle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GangnamStyleClient interface {
	Bid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Result(ctx context.Context, in *PlsResult, opts ...grpc.CallOption) (*Outcome, error)
	Bully(ctx context.Context, in *BullyRequest, opts ...grpc.CallOption) (*BullyResponse, error)
}

type gangnamStyleClient struct {
	cc grpc.ClientConnInterface
}

func NewGangnamStyleClient(cc grpc.ClientConnInterface) GangnamStyleClient {
	return &gangnamStyleClient{cc}
}

func (c *gangnamStyleClient) Bid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GangnamStyle_Bid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gangnamStyleClient) Result(ctx context.Context, in *PlsResult, opts ...grpc.CallOption) (*Outcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Outcome)
	err := c.cc.Invoke(ctx, GangnamStyle_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gangnamStyleClient) Bully(ctx context.Context, in *BullyRequest, opts ...grpc.CallOption) (*BullyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BullyResponse)
	err := c.cc.Invoke(ctx, GangnamStyle_Bully_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GangnamStyleServer is the server API for GangnamStyle service.
// All implementations must embed UnimplementedGangnamStyleServer
// for forward compatibility.
type GangnamStyleServer interface {
	Bid(context.Context, *Request) (*Response, error)
	Result(context.Context, *PlsResult) (*Outcome, error)
	Bully(context.Context, *BullyRequest) (*BullyResponse, error)
	mustEmbedUnimplementedGangnamStyleServer()
}

// UnimplementedGangnamStyleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGangnamStyleServer struct{}

func (UnimplementedGangnamStyleServer) Bid(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedGangnamStyleServer) Result(context.Context, *PlsResult) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedGangnamStyleServer) Bully(context.Context, *BullyRequest) (*BullyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bully not implemented")
}
func (UnimplementedGangnamStyleServer) mustEmbedUnimplementedGangnamStyleServer() {}
func (UnimplementedGangnamStyleServer) testEmbeddedByValue()                      {}

// UnsafeGangnamStyleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GangnamStyleServer will
// result in compilation errors.
type UnsafeGangnamStyleServer interface {
	mustEmbedUnimplementedGangnamStyleServer()
}

func RegisterGangnamStyleServer(s grpc.ServiceRegistrar, srv GangnamStyleServer) {
	// If the following call pancis, it indicates UnimplementedGangnamStyleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GangnamStyle_ServiceDesc, srv)
}

func _GangnamStyle_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GangnamStyleServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GangnamStyle_Bid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GangnamStyleServer).Bid(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GangnamStyle_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlsResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GangnamStyleServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GangnamStyle_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GangnamStyleServer).Result(ctx, req.(*PlsResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _GangnamStyle_Bully_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BullyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GangnamStyleServer).Bully(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GangnamStyle_Bully_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GangnamStyleServer).Bully(ctx, req.(*BullyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GangnamStyle_ServiceDesc is the grpc.ServiceDesc for GangnamStyle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GangnamStyle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gangnamStyle",
	HandlerType: (*GangnamStyleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "bid",
			Handler:    _GangnamStyle_Bid_Handler,
		},
		{
			MethodName: "result",
			Handler:    _GangnamStyle_Result_Handler,
		},
		{
			MethodName: "bully",
			Handler:    _GangnamStyle_Bully_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
